/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SearchImport } from './routes/search'
import { Route as ProfileImport } from './routes/profile'
import { Route as MainImport } from './routes/main'
import { Route as LoginImport } from './routes/login'
import { Route as AboutUsImport } from './routes/aboutUs'
import { Route as Pages123ContactImport } from './routes/pages123/Contact'
import { Route as Pages123BlogImport } from './routes/pages123/Blog'
import { Route as Pages123IdImport } from './routes/pages123/$id'

// Create Virtual Routes

const AboutLazyImport = createFileRoute('/about')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const AboutLazyRoute = AboutLazyImport.update({
  path: '/about',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/about.lazy').then((d) => d.Route))

const SearchRoute = SearchImport.update({
  path: '/search',
  getParentRoute: () => rootRoute,
} as any)

const ProfileRoute = ProfileImport.update({
  path: '/profile',
  getParentRoute: () => rootRoute,
} as any)

const MainRoute = MainImport.update({
  path: '/main',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const AboutUsRoute = AboutUsImport.update({
  path: '/aboutUs',
  getParentRoute: () => rootRoute,
} as any)

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const Pages123ContactRoute = Pages123ContactImport.update({
  path: '/pages123/Contact',
  getParentRoute: () => rootRoute,
} as any)

const Pages123BlogRoute = Pages123BlogImport.update({
  path: '/pages123/Blog',
  getParentRoute: () => rootRoute,
} as any)

const Pages123IdRoute = Pages123IdImport.update({
  path: '/pages123/$id',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/aboutUs': {
      id: '/aboutUs'
      path: '/aboutUs'
      fullPath: '/aboutUs'
      preLoaderRoute: typeof AboutUsImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/main': {
      id: '/main'
      path: '/main'
      fullPath: '/main'
      preLoaderRoute: typeof MainImport
      parentRoute: typeof rootRoute
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileImport
      parentRoute: typeof rootRoute
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutLazyImport
      parentRoute: typeof rootRoute
    }
    '/pages123/$id': {
      id: '/pages123/$id'
      path: '/pages123/$id'
      fullPath: '/pages123/$id'
      preLoaderRoute: typeof Pages123IdImport
      parentRoute: typeof rootRoute
    }
    '/pages123/Blog': {
      id: '/pages123/Blog'
      path: '/pages123/Blog'
      fullPath: '/pages123/Blog'
      preLoaderRoute: typeof Pages123BlogImport
      parentRoute: typeof rootRoute
    }
    '/pages123/Contact': {
      id: '/pages123/Contact'
      path: '/pages123/Contact'
      fullPath: '/pages123/Contact'
      preLoaderRoute: typeof Pages123ContactImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexLazyRoute,
  AboutUsRoute,
  LoginRoute,
  MainRoute,
  ProfileRoute,
  SearchRoute,
  AboutLazyRoute,
  Pages123IdRoute,
  Pages123BlogRoute,
  Pages123ContactRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/aboutUs",
        "/login",
        "/main",
        "/profile",
        "/search",
        "/about",
        "/pages123/$id",
        "/pages123/Blog",
        "/pages123/Contact"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/aboutUs": {
      "filePath": "aboutUs.tsx"
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/main": {
      "filePath": "main.tsx"
    },
    "/profile": {
      "filePath": "profile.tsx"
    },
    "/search": {
      "filePath": "search.tsx"
    },
    "/about": {
      "filePath": "about.lazy.tsx"
    },
    "/pages123/$id": {
      "filePath": "pages123/$id.tsx"
    },
    "/pages123/Blog": {
      "filePath": "pages123/Blog.tsx"
    },
    "/pages123/Contact": {
      "filePath": "pages123/Contact.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
