/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SearchImport } from './routes/search'
import { Route as MainImport } from './routes/main'
import { Route as Pages123ContactImport } from './routes/pages123/Contact'
import { Route as Pages123IdImport } from './routes/pages123/$id'

// Create Virtual Routes

const AboutLazyImport = createFileRoute('/about')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const AboutLazyRoute = AboutLazyImport.update({
  path: '/about',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/about.lazy').then((d) => d.Route))

const SearchRoute = SearchImport.update({
  path: '/search',
  getParentRoute: () => rootRoute,
} as any)

const MainRoute = MainImport.update({
  path: '/main',
  getParentRoute: () => rootRoute,
} as any)

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const Pages123ContactRoute = Pages123ContactImport.update({
  path: '/pages123/Contact',
  getParentRoute: () => rootRoute,
} as any)

const Pages123IdRoute = Pages123IdImport.update({
  path: '/pages123/$id',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/main': {
      id: '/main'
      path: '/main'
      fullPath: '/main'
      preLoaderRoute: typeof MainImport
      parentRoute: typeof rootRoute
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutLazyImport
      parentRoute: typeof rootRoute
    }
    '/pages123/$id': {
      id: '/pages123/$id'
      path: '/pages123/$id'
      fullPath: '/pages123/$id'
      preLoaderRoute: typeof Pages123IdImport
      parentRoute: typeof rootRoute
    }
    '/pages123/Contact': {
      id: '/pages123/Contact'
      path: '/pages123/Contact'
      fullPath: '/pages123/Contact'
      preLoaderRoute: typeof Pages123ContactImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexLazyRoute,
  MainRoute,
  SearchRoute,
  AboutLazyRoute,
  Pages123IdRoute,
  Pages123ContactRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/main",
        "/search",
        "/about",
        "/pages123/$id",
        "/pages123/Contact"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/main": {
      "filePath": "main.tsx"
    },
    "/search": {
      "filePath": "search.tsx"
    },
    "/about": {
      "filePath": "about.lazy.tsx"
    },
    "/pages123/$id": {
      "filePath": "pages123/$id.tsx"
    },
    "/pages123/Contact": {
      "filePath": "pages123/Contact.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
